# Generated by Django 5.1.6 on 2025-03-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_deanofficeprofile_first_name_and_more'),
        ('teams', '0002_joinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='profiles.supervisorprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_requests', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'supervisor')},
            },
        ),
    ]
