# Generated by Django 5.1.6 on 2025-03-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
