# Generated by Django 5.1.6 on 2025-03-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_deanofficeprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Automation and Control', 'Automation and Control'), ('Information Systems', 'Information Systems'), ('Computer Engineering and Software', 'Computer Engineering and Software'), ('IT Management', 'IT Management'), ('Robotics and Mechatronics', 'Robotics and Mechatronics')], max_length=100, null=True),
        ),
    ]
