# Generated by Django 5.1.6 on 2025-04-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
