# Generated by Django 5.1.6 on 2025-03-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thesis_topic', to='profiles.studentprofile')),
                ('created_by_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.supervisorprofile')),
                ('required_skills', models.ManyToManyField(related_name='thesis_topics', to='profiles.skill')),
            ],
        ),
    ]
