# Generated by Django 5.1.6 on 2025-03-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesistopic',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thesistopic',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
